version: '3.7'
services:

#  nginx:
#    image: nginx:1.17.2-alpine
#    ports:
#      - '80:80'
#    volumes:
#      - ./webapp:/var/www/html
#      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - php
#      - pgsql
#      - redis
#    networks:
#      code-network:

# Apache Service
  apache:
    build: './apache2/'
    container_name: docker_apache
    depends_on:
      - php
      - pgsql
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./webapp:/var/www/html
      - ./webapp/log:/var/log
    networks:
      code-network:

#  php:
#    build: ./php
#    user: '1000:1000'
#    volumes:
#      - ./webapp:/var/www/html
#      - ./php/php.ini-development:/usr/local/etc/php/php.ini-development
#      - ./php/php.ini-production:/usr/local/etc/php/php.ini-production
#      - ./php/docker-php-ext-sodium.ini:/usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
#    networks:
#      code-network:
#      vn:

  php:
    build: ./php7apache
    container_name: docker_php_apache
    user: '1000:1000'
    volumes:
      - ./webapp:/var/www/html
      - ./php/php.ini-development:/usr/local/etc/php/php.ini-development
      - ./php/php.ini-production:/usr/local/etc/php/php.ini-production
      - ./php/docker-php-ext-sodium.ini:/usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
    networks:
      code-network:
      vn:

  pgsql:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: dax
      POSTGRES_PASSWORD: dax
      POSTGRES_DB: dax
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      - code-network

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379

networks:
  code-network:
    driver: bridge
  vn:
    external:
      name: docker_vn